### ISSUE TITLE
image not showing on web page?

### ISSUE THREAD

**Issue by cole-brokamp** [degauss-org/geocoder#10]
The pages site isn't able to show the DeGAUSS logo for some reason?

![image](https://user-images.githubusercontent.com/4367617/118034844-6fca4700-b338-11eb-96c7-832bb3c9505a.png)

**Comment by erikarasnick** [comment]
not sure what's happening here... I tried moving the image to this repository (as opposed to linking to the degauss template repo) but it's still not showing up. I will investigate.

**Comment by erikarasnick** [comment]
okay, fixed using src='degauss_hex.png' instead of the long path to the repo
