### ISSUE TITLE
Windows 10 binding/credential issue

### ISSUE THREAD

**Issue by stu125** [degauss-org/geocoder#13]
A while back I ran into an issue where the drive wasn't shared in my Docker Settings which caused the binding to fail and the R script was returning that my csv file didn't exists.  Today I had a variant of that issue:

> PS C:\DeGauss> docker run --rm -v ${PWD}:/tmp degauss/geocoder ADDRESSES_TO_GEOCODE_BMI_2021_08_30.csv address
> Loading required package: methods
> Error in file(file, "rt") : cannot open the connection
> Calls: read.csv -> read.table -> file
> In addition: Warning message:
> In file(file, "rt") :
>   cannot open file 'ADDRESSES_TO_GEOCODE_BMI_2021_08_30.csv': No such file or directory
> Execution halted

In settings the the drive was marked as shared, however, I had to press "Reset Credentials" and reshare the drive to get it to work.  The only thing I can think of is I had to update my password which perhaps necessitated the reset.  Issue is resolved for me but might help others if they are running into a similar problem on a Windows machine.

**Comment by cole-brokamp** [comment]
thanks for reporting!
