### ISSUE TITLE
Degauss running in HPC using Singularity

### ISSUE THREAD

**Issue by XiyueL** [degauss-org/geocoder#19]
Hello Degauss team,

Our team was trying to practice Degauss in our HPC system. Due to compliance we could not use Docker but used Singularity to run the docker image instead. The program could run and shows the "Now geocoding" message but the progress bar never moved. I am wondering if this is more likely to be an insufficient memory issue or it could because of using Singularity instead of Docker? If it is because of insufficient memory, how much memory will it likely to take? 

Thanks for your help in advance!

**Comment by cole-brokamp** [comment]
Hi, geocoding shouldn't require a lot of memory.  Have you seen this implementation of the geocoder in Singularity?  It could work for you: https://cloud.sylabs.io/library/izahn/default/degauss_geocoder

Also, see here for some more discussion on the issue, including a singularity definition file created by @izahn: https://github.com/cole-brokamp/mappp/issues/2
