### ISSUE TITLE
implement {mappp}

### ISSUE THREAD

**Issue by erikarasnick** [degauss-org/geocoder#20]
implement [mappp](https://github.com/cole-brokamp/mappp) here and in other containers

**Comment by cole-brokamp** [comment]
the windows functionality (where it auto reverts to 1 core) will not work when using {mappp} within a docker container... how can we fix this?  we need some way to get info about the host in docker?

**Comment by cole-brokamp** [comment]
I snuck this in with #25, so will be closed soon. based on our conversations yesterday, I don't think it is a good idea to use mappp in all other containers
