### ISSUE TITLE
Updating TIGER/line shape files to 2021

### ISSUE THREAD

**Issue by kprybol** [degauss-org/geocoder#21]
Is it possible to update the database to use the recently released [2021 TIGER/line shape files](https://www.census.gov/geographies/mapping-files/time-series/geo/tiger-line-file.2021.html)? Would be willing to contribute by rebuilding the database + submitting a pull request. Would I need to self-host the updated database?

**Comment by cole-brokamp** [comment]
Yes, we would definitely be open to this pull request!  I would also be glad to host it publicly in a similar manner to how we do it now: https://github.com/degauss-org/geocoder/blob/142ee43090337665c2417e76e1420501ea80a9d1/Dockerfile#L3

**Comment by kprybol** [comment]
Following all of the instructions for [manually installing](https://github.com/degauss-org/degauss-org.github.io/wiki/Manual-Geocoder-Installation) (or as close as I could, some of the commands don't run as written), but running into an issue when trying to rebuild the database: 

```
sudo build/tiger_import /opt/geocoder.db TIGER2021
--- 01001
build/tiger_import: line 54: src/shp2sqlite/shp2sqlite: No such file or directory
Error: build/../lib/geocoder/us/sqlite3.so: cannot open shared object file: No such file or directory
memory
```
which points to: 
```
       # Convert each Shapefile into SQL statements.
	${SHP2SQLITE} -aS ${TMP}/*_${file}.shp tiger_${file}
     done && \
     for file in $DBFS; do
``` 

Any ideas as to why this is breaking?

**Comment by cole-brokamp** [comment]
Is the `lib/geocoder/us/sqlite3.so` file there?  Could be an incorrect reference to where the executable file is?

**Comment by kprybol** [comment]
Ah, no that appears to be missing. How do I get that installed? Both of these commands fail when attempting to compile the SQLite3 extension and the Geocoder-US Ruby gem. Could that be the culprit?  

```
kevinprybol@ubuntu:~/degauss/geocoder$ sudo make install
make: *** No rule to make target 'install'.  Stop.
kevinprybol@ubuntu:~/degauss/geocoder$ sudo gem install Geocoder-US-2.0.4.gem
ERROR:  Could not find a valid gem 'Geocoder-US-2.0.4.gem' (>= 0) in any repository
```

**Comment by cole-brokamp** [comment]
yes,  i would suppose that is the problem.
