### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by cptribby** [degauss-org/geocoder#34]
Getting the following error message. Checked your Troubleshooting, but not listed. Any help would be appreciated, thanks.

── Welcome to DeGAUSS! ──

• You are using geocoder, version 3.2.0
• This container returns geocodes      
• <https://degauss.org/geocoder>       

Error: 
      Usage:
      entrypoint.R <filename> [<score_threshold>]
      
Execution halted

**Comment by cole-brokamp** [comment]
Could you please provide an example DeGAUSS command and example input data file that caused this error? That way, we can reproduce it and help troubleshoot it.

**Comment by cptribby** [comment]
Yes, of course, here is the DeGUASS command: 
docker run --rm -v ${PWD}:/tmp ghcr.io/degauss-org/geocoder:3.2.0 addresses.csv

Sample addresses attached
[addresses.csv](https://github.com/degauss-org/geocoder/files/8766531/addresses.csv)

Thank you

**Comment by cole-brokamp** [comment]
When I run that command with your example file, I do not experience any errors:

```
  > docker run --rm -v ${PWD}:/tmp ghcr.io/degauss-org/geocoder:3.2.0 addresses.csv
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

── Welcome to DeGAUSS! ──

• You are using geocoder, version 3.2.0
• This container returns geocodes
• <https://degauss.org/geocoder>

ℹ removing non-alphanumeric characters...
ℹ removing excess whitespace...
ℹ flagging PO boxes...
ℹ flagging known Cincinnati foster & institutional addresses...
ℹ flagging non-address text and missing addresses...
ℹ now geocoding ...
  |===================================| 100%, Elapsed 00:18
ℹ geocoding complete; now filtering to precise geocodes...
✔ FINISHED! output written to addresses_geocoder_3.2.0_score_threshold_0.5.csv
ℹ 4 of 235 (1.7%) addresses were successfully geocoded. See detailed summary
below.


|geocode_result    |n (%)      |
|:-----------------|:----------|
|non_address_text  |230 (97.9) |
|imprecise_geocode |1 (0.4)    |
|geocoded          |4 (1.7)    |


```

Could you paste the full output you get after running the command?

**Comment by cole-brokamp** [comment]
Also, our [recommended](https://degauss.org/geocoder/#using) DeGAUSS call does not include braces around `PWD` (unless you are you are using [windows powershell](https://degauss.org/troubleshooting.html#PWD)).  Is that possibly an issue?

**Comment by cole-brokamp** [comment]
It was spaces in the filename.  If the spaces in your degauss command were not escaped properly (`\ `) then docker will think you are trying to pass multiple arguments delimited by spaces and cause the error.  This should work (although avoiding spaces in filenames is always a good idea for this exact reason):

```
docker run --rm -v ${PWD}:/tmp ghcr.io/degauss-org/geocoder:3.2.0 Copy\ of\ Mailing\ addresses\ COVID_25APR2022.csv.
```

You could also quote the name of the file.  I'm not sure if this is applicable to Windows or not.
