### ISSUE TITLE
PO Boxes

### ISSUE THREAD

**Issue by stu125** [degauss-org/geocoder#36]
The addresses flagged as PO Boxes skip the geocoding process.  There are sets of addresses, tend to be in rural areas, where a PO Box is included in the address.  It would be nice to have those addresses geocoded and then remove them after the fact using a filter on a PO Box flag if appropriate for the application.

**Comment by cole-brokamp** [comment]
Thanks, can you give an example of an address that would fall into this category?  Would rural addresses grouped by PO boxes still be representative of their residential location?  I'm worried that they are similar to urban post office boxes in that they don't represent residential location as well.
