### ISSUE TITLE
cannot create fifo '/tmp/RtmpOtAgQi/file...', reason 'Input/output error' Execution halted

### ISSUE THREAD

**Issue by Amro-Hassan** [degauss-org/geocoder#39]
I keep getting this error message on the sample file,any thoughts ?
CMD:  docker run --rm -v "%cd%":/tmp degauss/geocoder:3.0.1 sample_users.csv

Error in fifo(tempfile(), open = "w+b", blocking = T) :
  cannot open the connection
Calls: <Anonymous> -> mclapply_pb -> fifo
In addition: Warning message:
In fifo(tempfile(), open = "w+b", blocking = T) :
  cannot create fifo '/tmp/RtmpOtAgQi/file13fd274d9', reason 'Input/output error'
Execution halted

**Comment by cole-brokamp** [comment]
transferring this over to the geocoder repository, let me know if that doesn't seem correct.

your issue seems to be related to the inability of Windows to support parallel processing through forking.  set Docker Desktop preferences to only use one single core and this should fix the problem.

**Comment by Amro-Hassan** [comment]
Worked perfectly,Thank you @cole-brokamp

**Comment by cole-brokamp** [comment]
glad to help, this is the nudge we needed to add this back into our Windows-specific troubleshooting documentation.  thanks for bringing it up here!
