### ISSUE TITLE
Out of date reference maps

### ISSUE THREAD

**Issue by degoin** [degauss-org/geocoder#4]
Some streets have been renamed and/or constructed recently, and therefore the geocoder does not successfully geocode people living on them.

**Comment by cole-brokamp** [comment]
Thanks for opening this here!  We will work on updating this in the future.

**Comment by degoin** [comment]
Are there any updates on the status of this issue? Thanks very much.

**Comment by cole-brokamp** [comment]
No, unfortunately we lack the support of time needed to make this happen currently.  Pull requests always open though 😃 

It would be done through importing TIGER files from a different year and rebuilding the database as seen here:

https://github.com/cole-brokamp/geocoder#building-tigerline-database

**Comment by cole-brokamp** [comment]
Version 3.0 has just been release and uses updated TIGER/Line files from 2019.
