### ISSUE TITLE
Manual Geocoder Installation

### ISSUE THREAD

**Issue by Helen-Jiahuan-H** [degauss-org/geocoder#51]
Hello,

I was trying to manually install geocoded on CentOS 7 on my virtual R studio (a virtual machine) by following the instructions on this webpage: https://degauss.org/manual_install.html. However, I encountered some problems that I'm not able to solve by myself, so I'm seeking for help here.

Among the very last few steps on the instructions (https://degauss.org/manual_install.html), after I typed the command "git clone https://github.com/cole-brokamp/geocoder", I got an output requiring me to enter my GitHub username and password, but there is no response when I typed any key on the keyboard. I tried other repositories as well, such as "https://github.com/degauss-org/dht" and "https://github.com/degauss-org/geocoder", I was able to clone these two, but when I typed "sudo make install", I had an error saying "No rule to make target `install'. Stop.". Does this mean I have to edit the Makefile to have an "install" command? If so, how should I edit it? 
<img width="588" alt="prompts for logging into github" src="https://github.com/degauss-org/geocoder/assets/136014224/6c7e9fea-3fe8-4e6c-8adf-467198e105e9">

<img width="580" alt="sudo make install" src="https://github.com/degauss-org/geocoder/assets/136014224/fa02e2af-abfa-49ba-b7e3-7011761f07df">

Thank you very much in advance and I look forward to any suggestions!

**Comment by cole-brokamp** [comment]
sorry, we don't have any way to test installation instructions for CentOS7; let us know if you'd like to update it.

**Comment by jamesmb99** [comment]
Hello @cole-brokamp, seems like https://github.com/cole-brokamp/geocode is a private repository? If yes, how can I have access to the repo? This repository is listed in the instructions https://degauss.org/manual_install.html but I cannot clone it or access it over the browser.

Thank you in advance!

**Comment by cole-brokamp** [comment]
It is located at https://github.com/geomarker-io/geocoder now.  I wasn't really thinking and made a new R package called geocoder, so the URL forwarding from github broke.

**Comment by jamesmb99** [comment]
Thanks @cole-brokamp for the response. I'm still getting a "404" when I try to access https://github.com/geomarker-io/geocoder . Is it a private repo, if yes can I have access to it?

**Comment by jamesmb99** [comment]
Or maybe the new geocoder package that you made maybe what we are looking. Where is it hosted and how is it called? We are trying to look for an offline geocoding R package that does not require the use of a docker container like Degauss, since the R studio we are using is already in a docker container and using the DIND approach is adding more layers of difficulty.  

Thank your replies and guidance. Much appreciated!

**Comment by cole-brokamp** [comment]
gosh, I'm sorry -- it should be https://github.com/degauss-org/geocoder

the new package was an experiment and currently doesn't work to geocode.  I don't know of an offline geocoder R package that doesn't use Docker, but let me know if you come across anything, thanks!
