### ISSUE TITLE
Error "Column 1 must be named" when using geocoder

### ISSUE THREAD

**Issue by Helen-Jiahuan-H** [degauss-org/geocoder#53]
Hello,

I'm trying to run the geocoder function in the terminal within a virtual R environment. I typed the command as "sudo docker run -rm -v $PWD:/tmp ghcr.io/degauss-org/geocoder:3.3.0 test_addresses.csv", but I have the error shown as following, and I obtaining the error "! Column 1 must be named." (please see the output below).

<img width="873" alt="Screenshot 2023-11-09 at 1 18 47 PM" src="https://github.com/degauss-org/geocoder/assets/136014224/081c9e8e-5e2b-4810-9189-ea452bfe93b8">
<img width="818" alt="Screenshot 2023-11-09 at 1 19 07 PM" src="https://github.com/degauss-org/geocoder/assets/136014224/a42dd0f7-abb4-47f1-a1fa-ae8a556c831d">
<img width="837" alt="Screenshot 2023-11-09 at 1 19 15 PM" src="https://github.com/degauss-org/geocoder/assets/136014224/7f81ad09-dce8-4265-afd4-2589754e3d9b">

And below is what I have in the "test_addresses.csv", which is the csv file that contains my addresses:
<img width="477" alt="Screenshot 2023-11-09 at 1 24 21 PM" src="https://github.com/degauss-org/geocoder/assets/136014224/99622f9e-e03b-4693-b580-452f0a3e569e">

I'm confused because my first column, which is my column "id", is named as "id". 

Do you have any insights on how to fix this problem? Thank you so much and I would greatly appreciate your help!

Best,
Helen

**Comment by cole-brokamp** [comment]
Hi Helen,  the error message suggests that the file is not in the specified directory.  Could you share the file that produces your error instead of a screenshot of it?

Please note that using `sudo` runs the command as a different user. That would change the definition of `$PWD`, which could explain the error that it cannot find the file.

**Comment by Helen-Jiahuan-H** [comment]
> Hi Helen, the error message suggests that the file is not in the specified directory. Could you share the file that produces your error instead of a screenshot of it?
> 
> Please note that using `sudo` runs the command as a different user. That would change the definition of `$PWD`, which could explain the error that it cannot find the file.

Hi Dr. Brokamp,

Thank you for your reply! Yes, I have attached the csv file here below:
[test_addresses.csv](https://github.com/degauss-org/geocoder/files/13340902/test_addresses.csv)
I'm not sure why but it seems that after I recreated this csv file, it is now working without the error. 

However, for the other csv file below: 
([copy_addresses.csv](https://github.com/degauss-org/geocoder/files/13341149/copy_addresses.csv)), 
when I geocoded it, it still gives me that error, shown as the screenshots below:
<img width="680" alt="Screenshot 2023-11-13 at 3 39 45 PM" src="https://github.com/degauss-org/geocoder/assets/136014224/be1e84b6-7aca-4044-85ee-04a87d995e84">
<img width="672" alt="Screenshot 2023-11-13 at 3 39 57 PM" src="https://github.com/degauss-org/geocoder/assets/136014224/0d8ea000-130d-44cc-849a-053fa5319af9">
<img width="675" alt="Screenshot 2023-11-13 at 3 40 07 PM" src="https://github.com/degauss-org/geocoder/assets/136014224/1c279200-a657-4b69-bdca-db3e9f99dfc5">

I'm not sure whether it is because the file could not be found since I uploaded this file to the working directory (the virtual environment that I am working in). But if so, or if it is because of any other problem, do you have any thoughts on how to approach them? Thank you very much in advance!

Best,
Helen

**Comment by cole-brokamp** [comment]
I can't reproduce the error even with the updated file:

<img width="1132" alt="image" src="https://github.com/degauss-org/geocoder/assets/4367617/37903333-1f34-4797-b84a-58ed7a0f0207">

Are you certain that there is not a problem with the CSV file you are creating?  The error seems like there may be a malformed line ending in the file or something that is making it not able to read it as a CSV file.
