### ISSUE TITLE
Reading address files from mapped network drive or Dropbox

### ISSUE THREAD

**Issue by ckcheng1** [degauss-org/geocoder#55]
Hi there,

**I have 2 questions:**

1. Do you have any suggestions for how I may be able to read address files into DeGAUSS geocoder from the mapped network share?
2. If there isn't a way to read from network drives, is there a way to have DeGAUSS geocoder read in address files from a cloud service, such as DropBox or OneDrive (online only, not synced to C: drive).

**What I have tried:**

I've been successful in running DeGAUSS using Windows Powershell commands on test address files saved to my local C: drive on my Windows desktop, including on files synced from DropBox or OneDrive to my local C: drive.  However, we would prefer to keep the address files on our secure mapped network share or a secure cloud service (my institution's Dropbox or OneDrive).  In spite of my efforts, I've been unsuccessful in running DeGAUSS geocoder on address files stored on a mapped network share. After navigating to the mapped network drive folder to set it as the working directory in Powershell, I run the command: 

docker run --rm -v ${PWD}:/tmp ghcr.io/degauss-org/geocoder:3.3.0 mfive2324addresses.csv 

This gives me error messages (see attachments)
Attachment 1 - error message if use root path
Attachment 2 - error message if use drive letter (e.g. U: drive)

![Screenshot 2024-06-04 134256_DeGAUSS error_empty section btw colons](https://github.com/degauss-org/geocoder/assets/150189004/a046b651-3407-406d-9c06-9f96223278c7)
![Screenshot 2024-06-04 134551_DeGAUSS error_file does not exist](https://github.com/degauss-org/geocoder/assets/150189004/0f905595-6fef-4517-be80-95000dd1f07a)

**Other things I've tried:**

1. Since I'm using WSL 2 mode in Docker Desktop (switching to Hyper V mode renders DeGAUSS unable to run), the file sharing tab is disabled, so I'm unable to tell Docker to recognize the mapped network drive.
2. I've also Google the issue and followed these steps to try to mount the network drive folder to the geocoder container but it fails at the password step: https://wynnelo.medium.com/mounting-a-windows-shared-folder-to-a-docker-container-999e237caabd

Thanks!

**Comment by cole-brokamp** [comment]
I believe you could mount a remote folder to a docker network, but I am unfamiliar with this.

The goal of DeGAUSS is to support geocoding and geomarker assessment on data that you have locally and are unable to share with another machine, so it might not be the best tool for the use case you describe here.
