### ISSUE TITLE
mounts denied 

### ISSUE THREAD

**Issue by HuipingVUMC** [degauss-org/geocoder#60]
The project data is big. So I split the data to be smaller chunk and run on Jupyter Notebook: 
1) data on one remote server folder(same to the File Sharing location) 
2) on docker desktop File Sharing, I browse to: /Volumes/HPLWork0/Wu/EV/EV_v2022/Code

# Run Docker for each split file
def run_docker_on_splits():
    split_files = [f for f in os.listdir() if f.startswith("my_address_file_part_") and f.endswith(".csv")]
    for file in split_files:
        subprocess.run([
            "docker", "run", "--rm", "-v", f"{os.getcwd()}:/tmp", "degauss/geocoder:3.0.2", file
        ])

WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
**docker: Error response from daemon: Mounts denied:** 
The path /Volumes/HPLWork0/Wu/EV/EV_v2022/Code is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.

How to resolve this Mounts denied problem? 

Thanks!
Huiping

**Comment by cole-brokamp** [comment]
Based on your error message, it looks like you can configure the shared paths from within Docker's preferences.  Did you try to look there an ensure that the path you are trying to mount are configured to be shared?

**Comment by HuipingVUMC** [comment]
Thanks so fast response professor Brokamp!

I know the path for File Sharing is correct. When I read in data to Python, that is the path. I don't know how that path can share with Docker.  Do you have some suggestion how can this be shared?  If IT add me to the Docker group, do you think will work? I really can't find one person around to give a clear answer.

Thanks!

**Comment by HuipingVUMC** [comment]
Thanks professor Brokamp again for help! 

One more question: I run following on cmd
docker run --rm -v "%cd%:/tmp" degauss/geocider:3.0.2 my_address_file_start.csv

The data didn't be break into chunk, the Docker didn't finish after more than 6 hours:
![Screenshot 2024-08-22 at 4 50 44 PM](https://github.com/user-attachments/assets/0b849d93-55e2-4302-895d-154fc5bf6ebd)

I saw the memory be used up to 90% on the process and 1/3 RAM be used. My guess is the data is too big for DeGAUSS container, so I didn't get the decoding output from this input data.

What is the ideal rows to run this step(only ID, start, address columns)? If 10000 row as one chunk, it is over 800 chunks. 

Thanks!
Huiping
